// unused
{
    parserClass="com.dune.lang.parser.DuneParser"
    parserUtilClass='com.dune.lang.parser.DuneParserUtil'

    // every class generated implement/extends these
    implements="com.dune.lang.core.DuneElement"
    extends="com.dune.lang.core.DuneElementImpl"

    // generate the types of the element here
    elementTypeHolderClass='com.dune.lang.core.psi.DuneTypes'
    // element
    elementTypeClass="com.dune.lang.core.OcElementType"
    // token
    tokenTypeClass="com.dune.lang.core.DuneTokenType"

    // prefix / suffix / output
    psiClassPrefix="Dune"
    psiImplClassSuffix="Impl"
    psiPackage="com.dune.lang.core.psi"
    psiImplPackage="com.dune.lang.core.psi.impl"

    tokens = [
        VAR_START       =  '%{'
        VAR_END         =  '}'
        COLON           =  ':'
        LPAREN          =  '('
        RPAREN          =  ')'
        EQUAL           =  '='
        SHARP           =  '#'
        ATOM            =  "regexp:[A-Za-z_0-9'&^!.\-/+\\]+"
        WHITE_SPACE     =  "regexp:([ \t\f]|\n|\r|\r\n)+"
        STRING          =  "regexp:\".*\""
        COMMENT         =  "regexp:(#;|#\||;)[^\r\n]*"
    ]
}

// empty rule to force generation
File ::=